# Generated by Django 4.0.3 on 2022-04-11 14:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cover', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MovieDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('poster', models.URLField()),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('genres', models.CharField(max_length=100)),
                ('average_grade', models.FloatField()),
                ('actors', models.CharField(max_length=1000)),
                ('roles', models.CharField(max_length=1000)),
                ('production_companies', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('imdb_link', models.URLField()),
                ('budget', models.FloatField()),
                ('release_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('movie_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('would_recommend', models.BooleanField(blank=True, default=True, null=True)),
                ('selected_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('movie_id', 'selected_list')},
            },
        ),
    ]
