# Generated by Django 4.0.3 on 2022-04-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_address_remove_profile_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
